version: '3'
services:
  blog:
    build: .
    ports: 
      - "8080:8080"
    environment: 
      - PORT=8080
      - MONGO_URL=mongodb://mongodb:27017/blog
  mongodb:
    image: "mongo:3.6"
    ports:
      - "29000:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume: